# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do |options|

    build_theme = options[:build_theme]
    # add actions here: https://docs.fastlane.tools/actions

#cocoapods
increment_version_number_in_plist
update_settings_bundle key: "theme",
                     value: build_theme
ipaName = "SettingsTest"
ipaName = (ipaName + "-" +  ENV["BUILD_NUMBER"]) unless ENV["BUILD_NUMBER"].nil? #{nameSuffix}_#{versionName}_#{buildNumber}.ipa"
ipaName += ".ipa"
puts "ipa file name is: " + ipaName
gym(scheme: "SettingsTest",
  export_method: "development",
  configuration: "Release",
  clean: true,
  output_directory: "build",
  output_name: ipaName)

    upload_to_browserstack_app_live(
  browserstack_username: ENV["BROWSERSTACK_USERNAME"],
  browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
  file_path: "build/" + ipaName
)

upload_to_browserstack_app_automate(
browserstack_username: ENV["BROWSERSTACK_USERNAME"],
browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
file_path: "build/" + ipaName,
custom_id: "SettingsTest-" + build_theme
)

clean_build_artifacts
  end
end
