# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions

#cocoapods
increment_version_number_in_plist
update_settings_bundle key: "theme",
                     value: "green"
gym(scheme: "SettingsTest",
  export_method: "development",
  configuration: "Release",
  clean: true,
  output_directory: "build")

    upload_to_browserstack_app_live(
  browserstack_username: ENV["BROWSERSTACK_USERNAME"],
  browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
  file_path: "/Users/samiran/Documents/se/repos/SettingsBundleTest/build/SettingsTest.ipa"
)

upload_to_browserstack_app_automate(
browserstack_username: ENV["BROWSERSTACK_USERNAME"],
browserstack_access_key: ENV["BROWSERSTACK_ACCESS_KEY"],
file_path: "/Users/samiran/Documents/se/repos/SettingsBundleTest/build/SettingsTest.ipa",
custom_id: "SettingsTest"
)

clean_build_artifacts
  end
end
